//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syndic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depense
    {
        public int IdDepense { get; set; }
        public string Rubrique { get; set; }
        public string NomDepense { get; set; }
        public Nullable<System.DateTime> DateDepense { get; set; }
        public Nullable<double> MontantDepense { get; set; }
    
        public virtual Rubrique Rubrique1 { get; set; }
    }
}
