//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syndic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int IdP { get; set; }
        public Nullable<int> CinCop { get; set; }
        public Nullable<int> NumLogement { get; set; }
        public string NomPayeur { get; set; }
        public Nullable<System.DateTime> Datepaiement { get; set; }
        public Nullable<double> MontatP { get; set; }
        public Nullable<int> NbrMois { get; set; }
    
        public virtual Coproprietaire Coproprietaire { get; set; }
        public virtual Logement Logement { get; set; }
    }
}
