//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syndic_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SyndicEntities : DbContext
    {
        public DB_SyndicEntities()
            : base("name=DB_SyndicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coproprietaire> Coproprietaires { get; set; }
        public virtual DbSet<Depense> Depenses { get; set; }
        public virtual DbSet<Logement> Logements { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Rubrique> Rubriques { get; set; }
    }
}
